baseURL = 'honeybadgeredu.github.io'
languageCode = 'en-us'
title = 'Badger Tech'
canonialURL = true

markup.highlight.noClasses = false

[[menus.main]]
name = 'contact'
pageRef = '/contact'
weight = 10
[[menus.main]]
name = 'about'
pageRef = '/about'
weight = 20